### PR TITLE
Make PSH template use Marshal.Copy & one-line array

### PR DESCRIPTION
**Pull request by busterb**
This ports @OJ's PR to the rex-powershell gem https://github.com/rapid7/metasploit-framework/pull/6578

### CODE REVIEW

**Comment by OJ** [comment]
Thank you @bcook-r7 !

**Comment by busterb** [comment]
This seems good to me. Can you confirm I did it right @OJ ?

**Review by OJ — APPROVED** [review]
This is great to me. :+1:

**Comment by busterb** [comment]
Thanks gem is merged, I'll do another PR on framework to wrap it up.

**Pull request merged**
